package com.mcservice.hubcore.utilities.chat;

import org.bukkit.ChatColor;

public final class ColorType {
	
    public static final String BLUE;
    public static final String AQUA;
    public static final String YELLOW;
    public static final String RED;
    public static final String GRAY;
    public static final String GOLD;
    public static final String GREEN;
    public static final String WHITE;
    public static final String BLACK;
    public static final String BOLD;
    public static final String ITALIC;
    public static final String STRIKE_THROUGH;
    public static final String RESET;
    public static final String MAGIC;
    public static final String OBFUSCATED;
    public static final String B;
    public static final String M;
    public static final String O;
    public static final String I;
    public static final String S;
    public static final String R;
    public static final String DARK_BLUE;
    public static final String DARK_AQUA;
    public static final String DARK_GRAY;
    public static final String DARK_GREEN;
    public static final String DARK_PURPLE;
    public static final String DARK_RED;
    public static final String D_BLUE;
    public static final String D_AQUA;
    public static final String D_GRAY;
    public static final String D_GREEN;
    public static final String D_PURPLE;
    public static final String D_RED;
    public static final String LIGHT_PURPLE;
    public static final String L_PURPLE;
    public static final String PINK;
    public static final String B_BLUE;
    public static final String B_AQUA;
    public static final String B_YELLOW;
    public static final String B_RED;
    public static final String B_GRAY;
    public static final String B_GOLD;
    public static final String B_GREEN;
    public static final String B_WHITE;
    public static final String B_BLACK;
    public static final String BD_BLUE;
    public static final String BD_AQUA;
    public static final String BD_GRAY;
    public static final String BD_GREEN;
    public static final String BD_PURPLE;
    public static final String BD_RED;
    public static final String BL_PURPLE;
    public static final String I_BLUE;
    public static final String I_AQUA;
    public static final String I_YELLOW;
    public static final String I_RED;
    public static final String I_GRAY;
    public static final String I_GOLD;
    public static final String I_GREEN;
    public static final String I_WHITE;
    public static final String I_BLACK;
    public static final String ID_RED;
    public static final String ID_BLUE;
    public static final String ID_AQUA;
    public static final String ID_GRAY;
    public static final String ID_GREEN;
    public static final String ID_PURPLE;
    public static final String IL_PURPLE;
    public static final String BLANK_LINE = "§8 §8 §1 §3 §3 §7 §8 §r";
    public static final String BL = "§8 §8 §1 §3 §3 §7 §8 §r";
    public static final String VAPE = "§8 §8 §1 §3 §3 §7 §8 §r";
    
    private ColorType() {
        throw new RuntimeException("Cannot instantiate a utility class.");
    }
    
    static {
        BLUE = ChatColor.BLUE.toString();
        AQUA = ChatColor.AQUA.toString();
        YELLOW = ChatColor.YELLOW.toString();
        RED = ChatColor.RED.toString();
        GRAY = ChatColor.GRAY.toString();
        GOLD = ChatColor.GOLD.toString();
        GREEN = ChatColor.GREEN.toString();
        WHITE = ChatColor.WHITE.toString();
        BLACK = ChatColor.BLACK.toString();
        BOLD = ChatColor.BOLD.toString();
        ITALIC = ChatColor.ITALIC.toString();
        STRIKE_THROUGH = ChatColor.STRIKETHROUGH.toString();
        RESET = ChatColor.RESET.toString();
        MAGIC = ChatColor.MAGIC.toString();
        OBFUSCATED = ColorType.MAGIC;
        B = ColorType.BOLD;
        M = ColorType.MAGIC;
        O = ColorType.MAGIC;
        I = ColorType.ITALIC;
        S = ColorType.STRIKE_THROUGH;
        R = ColorType.RESET;
        DARK_BLUE = ChatColor.DARK_BLUE.toString();
        DARK_AQUA = ChatColor.DARK_AQUA.toString();
        DARK_GRAY = ChatColor.DARK_GRAY.toString();
        DARK_GREEN = ChatColor.DARK_GREEN.toString();
        DARK_PURPLE = ChatColor.DARK_PURPLE.toString();
        DARK_RED = ChatColor.DARK_RED.toString();
        D_BLUE = ColorType.DARK_BLUE;
        D_AQUA = ColorType.DARK_AQUA;
        D_GRAY = ColorType.DARK_GRAY;
        D_GREEN = ColorType.DARK_GREEN;
        D_PURPLE = ColorType.DARK_PURPLE;
        D_RED = ColorType.DARK_RED;
        LIGHT_PURPLE = ChatColor.LIGHT_PURPLE.toString();
        L_PURPLE = ColorType.LIGHT_PURPLE;
        PINK = ColorType.L_PURPLE;
        B_BLUE = ColorType.BLUE + ColorType.B;
        B_AQUA = ColorType.AQUA + ColorType.B;
        B_YELLOW = ColorType.YELLOW + ColorType.B;
        B_RED = ColorType.RED + ColorType.B;
        B_GRAY = ColorType.GRAY + ColorType.B;
        B_GOLD = ColorType.GOLD + ColorType.B;
        B_GREEN = ColorType.GREEN + ColorType.B;
        B_WHITE = ColorType.WHITE + ColorType.B;
        B_BLACK = ColorType.BLACK + ColorType.B;
        BD_BLUE = ColorType.D_BLUE + ColorType.B;
        BD_AQUA = ColorType.D_AQUA + ColorType.B;
        BD_GRAY = ColorType.D_GRAY + ColorType.B;
        BD_GREEN = ColorType.D_GREEN + ColorType.B;
        BD_PURPLE = ColorType.D_PURPLE + ColorType.B;
        BD_RED = ColorType.D_RED + ColorType.B;
        BL_PURPLE = ColorType.L_PURPLE + ColorType.B;
        I_BLUE = ColorType.BLUE + ColorType.I;
        I_AQUA = ColorType.AQUA + ColorType.I;
        I_YELLOW = ColorType.YELLOW + ColorType.I;
        I_RED = ColorType.RED + ColorType.I;
        I_GRAY = ColorType.GRAY + ColorType.I;
        I_GOLD = ColorType.GOLD + ColorType.I;
        I_GREEN = ColorType.GREEN + ColorType.I;
        I_WHITE = ColorType.WHITE + ColorType.I;
        I_BLACK = ColorType.BLACK + ColorType.I;
        ID_RED = ColorType.D_RED + ColorType.I;
        ID_BLUE = ColorType.D_BLUE + ColorType.I;
        ID_AQUA = ColorType.D_AQUA + ColorType.I;
        ID_GRAY = ColorType.D_GRAY + ColorType.I;
        ID_GREEN = ColorType.D_GREEN + ColorType.I;
        ID_PURPLE = ColorType.D_PURPLE + ColorType.I;
        IL_PURPLE = ColorType.L_PURPLE + ColorType.I;
    }
}
